# Generated by Django 4.2.4 on 2023-08-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0002_video_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likevideo',
            name='dislike',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='likevideo',
            name='like',
            field=models.IntegerField(default=False),
        ),
    ]
