# Generated by Django 4.2.4 on 2023-08-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0003_alter_likevideo_dislike_alter_likevideo_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likevideo',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='likevideo',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
